---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/pv-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  volumeName: my-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multi
  template:
    metadata:
      labels:
        app: busybox-multi
    spec:
      containers:
      - name: busybox
        image: busybox:1.36.0
        command: ["/bin/sh", "-c"] 
        args:
            - |
              mkdir -p /shared
              date > /shared/data.txt
              while true; do
                date >> /shared/data.txt
                sleep 5
              done
        volumeMounts:
        - name: shared-volume
          mountPath: /shared
      - name: multitool
        image: wbitt/network-multitool
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p /shared
            while [ ! -f /shared/data.txt ]; do
              echo "Waiting for /shared/data.txt..."
              sleep 2
            done
            tail -f /shared/data.txt
        volumeMounts:
        - name: shared-volume
          mountPath: /shared
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: my-pvc